spring:

  datasource:
    url: jdbc:h2:tcp://localhost/~/security-session-management
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        defaul_batch_fetch_size: 1000

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: false

server:
  port: 9000
  servlet:
    session:
      timeout: 60s

logging:
  level:
    org.hibernate.SQL: debug